/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArtTag: typeof import('./src/components/ArtTag.vue')['default']
    ArtworkCard: typeof import('./src/components/ArtworksList/ArtworkCard.vue')['default']
    ArtworkLargeCard: typeof import('./src/components/ArtworksList/ArtworkLargeCard.vue')['default']
    ArtworkLargeList: typeof import('./src/components/ArtworksList/ArtworkLargeList.vue')['default']
    ArtworkList: typeof import('./src/components/ArtworksList/ArtworkList.vue')['default']
    AuthorCard: typeof import('./src/components/AuthorCard.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CommentsArea: typeof import('./src/components/Comment/CommentsArea.vue')['default']
    CommentSubmit: typeof import('./src/components/Comment/CommentSubmit.vue')['default']
    ErrorPage: typeof import('./src/components/ErrorPage.vue')['default']
    ExternalLink: typeof import('./src/components/ExternalLink.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    IFaSolidAngleDown: typeof import('~icons/fa-solid/angle-down')['default']
    IFaSolidAngleLeft: typeof import('~icons/fa-solid/angle-left')['default']
    IFaSolidArrowDown: typeof import('~icons/fa-solid/arrow-down')['default']
    IFaSolidBars: typeof import('~icons/fa-solid/bars')['default']
    IFaSolidBirthdayCake: typeof import('~icons/fa-solid/birthday-cake')['default']
    IFaSolidCheck: typeof import('~icons/fa-solid/check')['default']
    IFaSolidCrown: typeof import('~icons/fa-solid/crown')['default']
    IFaSolidExternalLinkAlt: typeof import('~icons/fa-solid/external-link-alt')['default']
    IFaSolidEye: typeof import('~icons/fa-solid/eye')['default']
    IFaSolidFingerprint: typeof import('~icons/fa-solid/fingerprint')['default']
    IFaSolidHeart: typeof import('~icons/fa-solid/heart')['default']
    IFaSolidHome: typeof import('~icons/fa-solid/home')['default']
    IFaSolidImage: typeof import('~icons/fa-solid/image')['default']
    IFaSolidImages: typeof import('~icons/fa-solid/images')['default']
    IFaSolidLaughWink: typeof import('~icons/fa-solid/laugh-wink')['default']
    IFaSolidListUl: typeof import('~icons/fa-solid/list-ul')['default']
    IFaSolidMapMarkerAlt: typeof import('~icons/fa-solid/map-marker-alt')['default']
    IFaSolidMinus: typeof import('~icons/fa-solid/minus')['default']
    IFaSolidParking: typeof import('~icons/fa-solid/parking')['default']
    IFaSolidPlus: typeof import('~icons/fa-solid/plus')['default']
    IFaSolidQuestionCircle: typeof import('~icons/fa-solid/question-circle')['default']
    IFaSolidRandom: typeof import('~icons/fa-solid/random')['default']
    IFaSolidSearch: typeof import('~icons/fa-solid/search')['default']
    IFaSolidSpinner: typeof import('~icons/fa-solid/spinner')['default']
    IFaSolidThumbsUp: typeof import('~icons/fa-solid/thumbs-up')['default']
    IFaSolidTimes: typeof import('~icons/fa-solid/times')['default']
    IFaSolidUser: typeof import('~icons/fa-solid/user')['default']
    IFaSolidVenusMars: typeof import('~icons/fa-solid/venus-mars')['default']
    LazyLoad: typeof import('./src/components/LazyLoad.vue')['default']
    ListLink: typeof import('./src/components/SideNav/ListLink.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NProgress: typeof import('./src/components/NProgress.vue')['default']
    Placeholder: typeof import('./src/components/Placeholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    ShowMore: typeof import('./src/components/ShowMore.vue')['default']
    SideNav: typeof import('./src/components/SideNav/SideNav.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
  }
}
