/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtTag: typeof import('./components/ArtTag.vue')['default']
    ArtworkCard: typeof import('./components/ArtworksList/ArtworkCard.vue')['default']
    ArtworkLargeCard: typeof import('./components/ArtworksList/ArtworkLargeCard.vue')['default']
    ArtworkLargeList: typeof import('./components/ArtworksList/ArtworkLargeList.vue')['default']
    ArtworkList: typeof import('./components/ArtworksList/ArtworkList.vue')['default']
    ArtworksByUser: typeof import('./components/ArtworksList/ArtworksByUser.vue')['default']
    AuthorCard: typeof import('./components/AuthorCard.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Comment: typeof import('./components/Comment/Comment.vue')['default']
    CommentsArea: typeof import('./components/Comment/CommentsArea.vue')['default']
    CommentSubmit: typeof import('./components/Comment/CommentSubmit.vue')['default']
    ErrorPage: typeof import('./components/ErrorPage.vue')['default']
    ExternalLink: typeof import('./components/ExternalLink.vue')['default']
    FollowUserCard: typeof import('./components/FollowUserCard.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    LazyLoad: typeof import('./components/LazyLoad.vue')['default']
    ListLink: typeof import('./components/SideNav/ListLink.vue')['default']
    NaiveuiProvider: typeof import('./components/NaiveuiProvider.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCountdown: typeof import('naive-ui')['NCountdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NInput: typeof import('naive-ui')['NInput']
    NLi: typeof import('naive-ui')['NLi']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('./components/NProgress.vue')['default']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NUl: typeof import('naive-ui')['NUl']
    Placeholder: typeof import('./components/Placeholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    ShowMore: typeof import('./components/ShowMore.vue')['default']
    SideNav: typeof import('./components/SideNav/SideNav.vue')['default']
    SiteFooter: typeof import('./components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./components/SiteHeader.vue')['default']
    SiteNoticeBanner: typeof import('./components/SiteNoticeBanner.vue')['default']
    UgoiraViewer: typeof import('./components/UgoiraViewer.vue')['default']
  }
}
